[2024-04-26 00:57:15,148: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-04-26 00:57:15,575: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 2.00 seconds... (1/100)

[2024-04-26 00:57:17,929: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 4.00 seconds... (2/100)

[2024-04-26 00:57:24,242: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 6.00 seconds... (3/100)

[2024-04-26 00:57:34,334: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 8.00 seconds... (4/100)

[2024-04-26 00:57:43,347: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 10.00 seconds... (5/100)

[2024-04-26 00:57:54,732: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 12.00 seconds... (6/100)

[2024-04-26 00:58:10,553: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 14.00 seconds... (7/100)

[2024-04-26 00:58:26,442: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 16.00 seconds... (8/100)

[2024-04-26 00:58:45,386: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 18.00 seconds... (9/100)

[2024-04-26 00:59:15,896: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 20.00 seconds... (10/100)

[2024-04-26 00:59:36,915: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 22.00 seconds... (11/100)

[2024-04-26 01:00:01,164: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 24.00 seconds... (12/100)

[2024-04-26 01:00:33,524: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 26.00 seconds... (13/100)

[2024-04-26 01:01:03,029: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 28.00 seconds... (14/100)

[2024-04-26 01:01:32,856: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 30.00 seconds... (15/100)

[2024-04-26 01:02:05,181: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 32.00 seconds... (16/100)

[2024-04-26 01:02:45,460: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 32.00 seconds... (16/100)

[2024-04-26 01:03:21,598: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 32.00 seconds... (16/100)

[2024-04-26 01:03:59,960: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 32.00 seconds... (16/100)

[2024-04-26 01:04:35,289: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 32.00 seconds... (16/100)

[2024-04-26 01:05:11,909: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Address not available..
Trying again in 32.00 seconds... (16/100)

[2024-04-26 01:17:02,958: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-04-26 01:17:03,797: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-04-26 01:17:03,857: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-04-26 01:17:03,951: INFO/MainProcess] mingle: searching for neighbors
[2024-04-26 01:17:05,147: INFO/MainProcess] mingle: all alone
[2024-04-26 01:17:07,118: INFO/MainProcess] celery@84b401575812 ready.
